name: Update docs

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The branch to create the dev tag on
        type: string
        required: true
#   push:
#     branches:
#       - master

jobs:
  create-docs:
    name: Update docs
    runs-on: ubuntu-latest

    outputs:
      constantsVersion: ${{ steps.versions.outputs.constantsVersion }}
      constantsVersionXy: ${{ steps.versions.outputs.constantsVersionXy }}
      setupVersion: ${{ steps.versions.outputs.setupVersion }}
      setupVersionXy: ${{ steps.versions.outputs.setupVersionXy }}
      newestVersion: ${{ steps.versions.outputs.newestVersion }}
      targetBranch: ${{ steps.versions.outputs.targetBranch }}
      devTag: ${{ steps.versions.outputs.devTag }}
      releaseTag: ${{ steps.versions.outputs.releaseTag }}
      versionFolder: ${{ steps.versions.outputs.versionFolder }}
      artifactName: ${{ steps.versions.outputs.artifactName }}

    steps:
      - uses: actions/checkout@v4

      - id: versions
        run: |
          . ./hooks/populate-hook-constants.sh

          echo "constantsVersion=$constantsVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
          echo "constantsVersionXy=$constantsVersionXy" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
          echo "setupVersion=$setupVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
          echo "setupVersionXy=$setupVersionXy" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
          echo "newestVersion=$newestVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
          echo "targetBranch=$targetBranch" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"

          echo "devTag=dev-v$setupVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
          echo "releaseTag=v$setupVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"

          echo "versionFolder=$setupVersionXy.X" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
          echo "artifactName=python-docs-$setupVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.versions.outputs.artifactName }}
          path: html/supertokens_python

  publish-docs:
    needs:
      - create-docs

    uses: supertokens/supertokens-backend-website/.github/workflows/release-python-documentation-changes.yml@feat/python-docs
    secrets: inherit
    with:
      version: ${{ needs.create-docs.outputs.setupVersion }}
      artifact-name: ${{ needs.create-docs.outputs.artifactName }}
      version-folder: ${{ needs.create-docs.outputs.versionFolder }}
      run-id: ${{ github.run_id }}
      stage: preview